name: wfcd_dart
repository: https://github.com/SlayerOrnstein/wfcd_dart

environment:
  sdk: "^3.10.0"

workspace:
  - packages/profile_models
  - packages/warframe_drop_data
  - packages/warframe_items
  - packages/warframe_worldstate_data
  - packages/worldstate_models
  - packages/worldstate_status

dev_dependencies:
  melos: ^7.3.0

melos:
  scripts:
    generate:
      run: melos exec --depends-on build_runner -- dart run build_runner build
    analyze:
      run: melos exec -- dart analyze --fatal-infos --fatal-warnings
    test:
      run: melos exec --depends-on test -- dart test
  command:
    version:
      branch: master
      updateGitTagRefs: true
      releaseUrl: true
      message: |
        chore(release): publish packages [skip ci]

        {new_package_versions}
