name: worldstate_models
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  collection: ^1.19.1
  crypto: ^3.0.6
  dart_mappable: ^4.6.1
  http: ^1.5.0
  time: ^2.1.5
  warframe_drop_data:
    path: ../warframe_drop_data
  warframe_worldstate_data:
    path: ../warframe_worldstate_data

dev_dependencies:
  build_runner: ^2.9.0
  dart_mappable_builder: ^4.6.1
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
