name: worldstate_status
description: A new Dart Frog application
version: 1.0.27
publish_to: none

environment:
  sdk: ^3.10.0

resolution: workspace

workspace:
  - packages/cache

dependencies:
  cache:
    path: packages/cache
  dart_frog: ^1.1.0
  http: ^1.5.0
  warframe_drop_data:
    git:
      url: https://github.com/SlayerOrnstein/wfcd_dart.git
      path: packages/warframe_drop_data
      ref: warframe_drop_data-v0.1.5
  worldstate_models:
    git:
      url: https://github.com/SlayerOrnstein/wfcd_dart.git
      path: packages/worldstate_models
      ref: worldstate_models-v0.1.5+8

dev_dependencies:
  dart_frog_lint: ^0.1.0
  mocktail: ^1.0.3
  test: ^1.25.5
