name: warframe_worldstate_data
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  collection: ^1.19.1
  slang: ^4.9.1

dev_dependencies:
  build_runner: ^2.9.0
  slang_build_runner: ^4.9.0
  test: ^1.26.3
  very_good_analysis: ^10.0.0
