name: warframe_drop_data
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  collection: ^1.19.1
  crypto: ^3.0.6
  dart_mappable: ^4.5.0
  html: ^0.15.5
  http: ^1.3.0

dev_dependencies:
  build_runner: ^2.4.15
  dart_mappable_builder: ^4.5.0
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^10.0.0
