// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'mission_types.dart';

// **************************************************************************
// StrEmbeddingGenerator
// **************************************************************************

const _$_en = r'''
{"MT_ARENA":{"value":"Rathuum"},"MT_ARTIFACT":{"value":"Disruption"},"MT_ASSAULT":{"value":"Assault"},"MT_ASSASSINATION":{"value":"Assassination"},"MT_CAPTURE":{"value":"Capture"},"MT_DEFENSE":{"value":"Defense"},"MT_DISRUPTION":{"value":"Disruption"},"MT_EVACUATION":{"value":"Defection"},"MT_EXCAVATE":{"value":"Excavation"},"MT_EXTERMINATION":{"value":"Extermination"},"MT_HIVE":{"value":"Hive"},"MT_INTEL":{"value":"Spy"},"MT_LANDSCAPE":{"value":"Free Roam"},"MT_MOBILE_DEFENSE":{"value":"Mobile Defense"},"MT_PVP":{"value":"Conclave"},"MT_RESCUE":{"value":"Rescue"},"MT_RETRIEVAL":{"value":"Hijack"},"MT_SABOTAGE":{"value":"Sabotage"},"MT_SECTOR":{"value":"Dark Sector"},"MT_SURVIVAL":{"value":"Survival"},"MT_TERRITORY":{"value":"Interception"},"MT_DEFAULT":{"value":"Unknown"},"MT_VOID_CASCADE":{"value":"Void Cascade"},"MT_ASCENSION":{"value":"Ascension"},"MT_ALCHEMY":{"value":"Alchemy"},"MT_ENDLESS_CAPTURE":{"value":"Legacyte Harvest"}}
''';

const _$_cs = r'''
{"MT_ARENA":{"value":"Rathuum"},"MT_ARTIFACT":{"value":"Disruption"},"MT_ASSAULT":{"value":"Assault"},"MT_ASSASSINATION":{"value":"Assassination"},"MT_CAPTURE":{"value":"Capture"},"MT_DEFENSE":{"value":"Defense"},"MT_DISRUPTION":{"value":"Disruption"},"MT_EVACUATION":{"value":"Defection"},"MT_EXCAVATE":{"value":"Excavation"},"MT_EXTERMINATION":{"value":"Extermination"},"MT_HIVE":{"value":"Hive"},"MT_INTEL":{"value":"Spy"},"MT_LANDSCAPE":{"value":"Free Roam"},"MT_MOBILE_DEFENSE":{"value":"Mobile Defense"},"MT_PVP":{"value":"Conclave"},"MT_RESCUE":{"value":"Rescue"},"MT_RETRIEVAL":{"value":"Hijack"},"MT_SABOTAGE":{"value":"Sabotage"},"MT_SECTOR":{"value":"Dark Sector"},"MT_SURVIVAL":{"value":"Survival"},"MT_TERRITORY":{"value":"Interception"},"MT_DEFAULT":{"value":"Unknown"},"MT_VOID_CASCADE":{"value":"Void Cascade"},"MT_ASCENSION":{"value":"Ascension"},"MT_ALCHEMY":{"value":"Alchemy"},"MT_ENDLESS_CAPTURE":{"value":"Legacyte Harvest"}}
''';

const _$_de = r'''
{"MT_ARENA":{"value":"Rathuum"},"MT_ARTIFACT":{"value":"Störung"},"MT_ASSAULT":{"value":"Sturmangriff"},"MT_ASSASSINATION":{"value":"Attentat"},"MT_CAPTURE":{"value":"Gefangennahme"},"MT_DEFENSE":{"value":"Verteidigung"},"MT_DISRUPTION":{"value":"Störung"},"MT_EVACUATION":{"value":"Seitenwechsel"},"MT_EXCAVATE":{"value":"Ausgrabung"},"MT_EXTERMINATION":{"value":"Auslöschung"},"MT_HIVE":{"value":"Hive"},"MT_INTEL":{"value":"Spionage"},"MT_LANDSCAPE":{"value":"Freies Erkunden"},"MT_MOBILE_DEFENSE":{"value":"Mobile Verteidigung"},"MT_PVP":{"value":"Conclave"},"MT_RESCUE":{"value":"Rettung"},"MT_RETRIEVAL":{"value":"Entführung"},"MT_SABOTAGE":{"value":"Sabotage"},"MT_SECTOR":{"value":"Dark Sector"},"MT_SURVIVAL":{"value":"Überleben"},"MT_TERRITORY":{"value":"Abfangen"},"MT_DEFAULT":{"value":"Unbekannt"},"MT_VOID_CASCADE":{"value":"Void Cascade"},"MT_ASCENSION":{"value":"Ascension"},"MT_ALCHEMY":{"value":"Alchemy"},"MT_ENDLESS_CAPTURE":{"value":"Legacyte Harvest"}}
''';

const _$_es = r'''
{"MT_ARENA":{"value":"Rathuum"},"MT_ARTIFACT":{"value":"Interrupción"},"MT_ASSAULT":{"value":"Asalto"},"MT_ASSASSINATION":{"value":"Asesinato"},"MT_CAPTURE":{"value":"Captura"},"MT_DEFENSE":{"value":"Defensa"},"MT_DISRUPTION":{"value":"Interrupción"},"MT_EVACUATION":{"value":"Deserción"},"MT_EXCAVATE":{"value":"Excavación"},"MT_EXTERMINATION":{"value":"Exterminio"},"MT_HIVE":{"value":"Colmena"},"MT_INTEL":{"value":"Espionaje"},"MT_LANDSCAPE":{"value":"Recorrido libre"},"MT_MOBILE_DEFENSE":{"value":"Defensa móvil"},"MT_PVP":{"value":"Cónclave"},"MT_RESCUE":{"value":"Rescate"},"MT_RETRIEVAL":{"value":"Usurpación"},"MT_SABOTAGE":{"value":"Sabotaje"},"MT_SECTOR":{"value":"Sector oscuro"},"MT_SURVIVAL":{"value":"Supervivencia"},"MT_TERRITORY":{"value":"Interceptación"},"MT_DEFAULT":{"value":"Desconocido"},"MT_VOID_CASCADE":{"value":"Cascada del Vacío"},"MT_ASCENSION":{"value":"Ascensión"},"MT_ALCHEMY":{"value":"Alquimia"},"MT_ENDLESS_CAPTURE":{"value":"Legacyte Harvest"}}
''';

const _$_fr = r'''
{"MT_ARENA":{"value":"Rathuum"},"MT_ARTIFACT":{"value":"Perturbation"},"MT_ASSAULT":{"value":"Assaut"},"MT_ASSASSINATION":{"value":"Assassinat"},"MT_CAPTURE":{"value":"Capture"},"MT_DEFENSE":{"value":"Défense"},"MT_DISRUPTION":{"value":"Perturbation"},"MT_EVACUATION":{"value":"Désertion"},"MT_EXCAVATE":{"value":"Excavation"},"MT_EXTERMINATION":{"value":"Extermination"},"MT_HIVE":{"value":"Ruche"},"MT_INTEL":{"value":"Espionnage"},"MT_LANDSCAPE":{"value":"Exploration Libre"},"MT_MOBILE_DEFENSE":{"value":"Défense Mobile"},"MT_PVP":{"value":"Conclave"},"MT_RESCUE":{"value":"Sauvetage"},"MT_RETRIEVAL":{"value":"Détournement"},"MT_SABOTAGE":{"value":"Sabotage"},"MT_SECTOR":{"value":"Dark Sector"},"MT_SURVIVAL":{"value":"Survie"},"MT_TERRITORY":{"value":"Interception"},"MT_DEFAULT":{"value":"Inconnu"},"MT_VOID_CASCADE":{"value":"Void Cascade"},"MT_ASCENSION":{"value":"Ascension"},"MT_ALCHEMY":{"value":"Alchemy"},"MT_ENDLESS_CAPTURE":{"value":"Legacyte Harvest"}}
''';

const _$_it = r'''
{"MT_ARENA":{"value":"Rathuum"},"MT_ARTIFACT":{"value":"Disruption"},"MT_ASSAULT":{"value":"Assalto"},"MT_ASSASSINATION":{"value":"Assassinio"},"MT_CAPTURE":{"value":"Cattura"},"MT_DEFENSE":{"value":"Difesa"},"MT_DISRUPTION":{"value":"Disruption"},"MT_EVACUATION":{"value":"Defection"},"MT_EXCAVATE":{"value":"Scavo"},"MT_EXTERMINATION":{"value":"Sterminio"},"MT_HIVE":{"value":"Alveare"},"MT_INTEL":{"value":"Spionaggio"},"MT_LANDSCAPE":{"value":"Free Roam"},"MT_MOBILE_DEFENSE":{"value":"Difesa Mobile"},"MT_PVP":{"value":"Conclave"},"MT_RESCUE":{"value":"Salvataggio"},"MT_RETRIEVAL":{"value":"Dirottamento"},"MT_SABOTAGE":{"value":"Sabotaggio"},"MT_SECTOR":{"value":"Settore Oscuro"},"MT_SURVIVAL":{"value":"Sopravvivenza"},"MT_TERRITORY":{"value":"Intercettazione"},"MT_DEFAULT":{"value":"Unknown"},"MT_VOID_CASCADE":{"value":"Void Cascade"},"MT_ASCENSION":{"value":"Ascension"},"MT_ALCHEMY":{"value":"Alchemy"},"MT_ENDLESS_CAPTURE":{"value":"Legacyte Harvest"}}
''';

const _$_ko = r'''
{"MT_ARENA":{"value":"라툼"},"MT_ARTIFACT":{"value":"Disruption"},"MT_ASSAULT":{"value":"맹공"},"MT_ASSASSINATION":{"value":"암살"},"MT_CAPTURE":{"value":"생포"},"MT_DEFENSE":{"value":"방어"},"MT_DISRUPTION":{"value":"Disruption"},"MT_EVACUATION":{"value":"탈주"},"MT_EXCAVATE":{"value":"발굴"},"MT_EXTERMINATION":{"value":"섬멸"},"MT_HIVE":{"value":"하이브"},"MT_INTEL":{"value":"첩보활동"},"MT_LANDSCAPE":{"value":"자유 탐험"},"MT_MOBILE_DEFENSE":{"value":"모바일 방어"},"MT_PVP":{"value":"콘클레이브"},"MT_RESCUE":{"value":"구출"},"MT_RETRIEVAL":{"value":"탈취"},"MT_SABOTAGE":{"value":"파괴공작"},"MT_SECTOR":{"value":"다크 섹터"},"MT_SURVIVAL":{"value":"생존"},"MT_TERRITORY":{"value":"감청"},"MT_DEFAULT":{"value":"Unknown"},"MT_VOID_CASCADE":{"value":"Void Cascade"},"MT_ASCENSION":{"value":"Ascension"},"MT_ALCHEMY":{"value":"Alchemy"},"MT_ENDLESS_CAPTURE":{"value":"Legacyte Harvest"}}
''';

const _$_pl = r'''
{"MT_ARENA":{"value":"Rathuum"},"MT_ARTIFACT":{"value":"Disruption"},"MT_ASSAULT":{"value":"Natarcie"},"MT_ASSASSINATION":{"value":"Zabójstwo"},"MT_CAPTURE":{"value":"Pojmanie"},"MT_DEFENSE":{"value":"Obrona"},"MT_DISRUPTION":{"value":"Disruption"},"MT_EVACUATION":{"value":"Defection"},"MT_EXCAVATE":{"value":"Wydobycie"},"MT_EXTERMINATION":{"value":"Eksterminacja"},"MT_HIVE":{"value":"Hive"},"MT_INTEL":{"value":"Infiltracja"},"MT_LANDSCAPE":{"value":"Free Roam"},"MT_MOBILE_DEFENSE":{"value":"Mobilna obrona"},"MT_PVP":{"value":"Konklawe"},"MT_RESCUE":{"value":"Ratunek"},"MT_RETRIEVAL":{"value":"Hijack"},"MT_SABOTAGE":{"value":"Sabotaż"},"MT_SECTOR":{"value":"Mroczny Sector"},"MT_SURVIVAL":{"value":"Przetrwanie"},"MT_TERRITORY":{"value":"Przechwycenie"},"MT_DEFAULT":{"value":"Unknown"},"MT_VOID_CASCADE":{"value":"Void Cascade"},"MT_ASCENSION":{"value":"Ascension"},"MT_ALCHEMY":{"value":"Alchemy"},"MT_ENDLESS_CAPTURE":{"value":"Legacyte Harvest"}}
''';

const _$_pt = r'''
{"MT_ARENA":{"value":"Rathuum"},"MT_ARTIFACT":{"value":"Disruption"},"MT_ASSAULT":{"value":"Assalto"},"MT_ASSASSINATION":{"value":"Assassinato"},"MT_CAPTURE":{"value":"Captura"},"MT_DEFENSE":{"value":"Defesa"},"MT_DISRUPTION":{"value":"Disruption"},"MT_EVACUATION":{"value":"Defection"},"MT_EXCAVATE":{"value":"Escavação"},"MT_EXTERMINATION":{"value":"Extermínio"},"MT_HIVE":{"value":"Colmeia"},"MT_INTEL":{"value":"Espionagem"},"MT_LANDSCAPE":{"value":"Free Roam"},"MT_MOBILE_DEFENSE":{"value":"Defesa Móvel"},"MT_PVP":{"value":"Conclave"},"MT_RESCUE":{"value":"Resgate"},"MT_RETRIEVAL":{"value":"Extravio"},"MT_SABOTAGE":{"value":"Sabotagem"},"MT_SECTOR":{"value":"Dark Sector"},"MT_SURVIVAL":{"value":"Sobrevivência"},"MT_TERRITORY":{"value":"Interceptação"},"MT_DEFAULT":{"value":"Unknown"},"MT_VOID_CASCADE":{"value":"Void Cascade"},"MT_ASCENSION":{"value":"Ascension"},"MT_ALCHEMY":{"value":"Alchemy"},"MT_ENDLESS_CAPTURE":{"value":"Legacyte Harvest"}}
''';

const _$_ru = r'''
{"MT_ARENA":{"value":"Ратуум"},"MT_ARTIFACT":{"value":"Сбой"},"MT_ASSAULT":{"value":"Штурм"},"MT_ASSASSINATION":{"value":"Убийство"},"MT_CAPTURE":{"value":"Захват"},"MT_DEFENSE":{"value":"Оборона"},"MT_DISRUPTION":{"value":"Сбой"},"MT_EVACUATION":{"value":"Перебежчики"},"MT_EXCAVATE":{"value":"Раскопки"},"MT_EXTERMINATION":{"value":"Зачистка"},"MT_HIVE":{"value":"Улей"},"MT_INTEL":{"value":"Шпионаж"},"MT_LANDSCAPE":{"value":"Свободное перемещение"},"MT_MOBILE_DEFENSE":{"value":"Мобильная Оборона"},"MT_PVP":{"value":"Конклав"},"MT_RESCUE":{"value":"Спасение"},"MT_RETRIEVAL":{"value":"Угон"},"MT_SABOTAGE":{"value":"Диверсия"},"MT_SECTOR":{"value":"Темный Сектор"},"MT_SURVIVAL":{"value":"Выживание"},"MT_TERRITORY":{"value":"Перехват"},"MT_DEFAULT":{"value":"Неизвестно"},"MT_VOID_CASCADE":{"value":"Void Cascade"},"MT_ASCENSION":{"value":"Ascension"},"MT_ALCHEMY":{"value":"Alchemy"},"MT_ENDLESS_CAPTURE":{"value":"Legacyte Harvest"}}
''';

const _$_sr = r'''
{"MT_ARENA":{"value":"Rathuum"},"MT_ARTIFACT":{"value":"Disruption"},"MT_ASSAULT":{"value":"Assault"},"MT_ASSASSINATION":{"value":"Assassination"},"MT_CAPTURE":{"value":"Capture"},"MT_DEFENSE":{"value":"Defense"},"MT_DISRUPTION":{"value":"Disruption"},"MT_EVACUATION":{"value":"Defection"},"MT_EXCAVATE":{"value":"Excavation"},"MT_EXTERMINATION":{"value":"Extermination"},"MT_HIVE":{"value":"Hive"},"MT_INTEL":{"value":"Spy"},"MT_LANDSCAPE":{"value":"Free Roam"},"MT_MOBILE_DEFENSE":{"value":"Mobile Defense"},"MT_PVP":{"value":"Conclave"},"MT_RESCUE":{"value":"Rescue"},"MT_RETRIEVAL":{"value":"Hijack"},"MT_SABOTAGE":{"value":"Sabotage"},"MT_SECTOR":{"value":"Dark Sector"},"MT_SURVIVAL":{"value":"Survival"},"MT_TERRITORY":{"value":"Interception"},"MT_DEFAULT":{"value":"Unknown"},"MT_VOID_CASCADE":{"value":"Void Cascade"},"MT_ASCENSION":{"value":"Ascension"},"MT_ALCHEMY":{"value":"Alchemy"},"MT_ENDLESS_CAPTURE":{"value":"Legacyte Harvest"}}
''';

const _$_tr = r'''
{"MT_ARENA":{"value":"Rathuum"},"MT_ARTIFACT":{"value":"Kargaşa"},"MT_ASSAULT":{"value":"Saldırı"},"MT_ASSASSINATION":{"value":"Suikast"},"MT_CAPTURE":{"value":"Ele Geçirme"},"MT_DEFENSE":{"value":"Savunma"},"MT_DISRUPTION":{"value":"Kargaşa"},"MT_EVACUATION":{"value":"Sığınma"},"MT_EXCAVATE":{"value":"Kazı"},"MT_EXTERMINATION":{"value":"Yok Etme"},"MT_HIVE":{"value":"Kovan"},"MT_INTEL":{"value":"Casus"},"MT_LANDSCAPE":{"value":"Serbest Dolaşım"},"MT_MOBILE_DEFENSE":{"value":"Mobil Savunma"},"MT_PVP":{"value":"Conclave"},"MT_RESCUE":{"value":"Kurtarma"},"MT_RETRIEVAL":{"value":"Kaçırma"},"MT_SABOTAGE":{"value":"Sabotaj"},"MT_SECTOR":{"value":"Dark Sector"},"MT_SURVIVAL":{"value":"Hayatta Kalma"},"MT_TERRITORY":{"value":"Engelleme"},"MT_DEFAULT":{"value":"Unknown"},"MT_VOID_CASCADE":{"value":"Void Cascade"},"MT_ASCENSION":{"value":"Ascension"},"MT_ALCHEMY":{"value":"Alchemy"},"MT_ENDLESS_CAPTURE":{"value":"Legacyte Harvest"}}
''';

const _$_uk = r'''
{"MT_ARENA":{"value":"Ратум"},"MT_ARTIFACT":{"value":"Завада підриву"},"MT_ASSAULT":{"value":"Штурм"},"MT_ASSASSINATION":{"value":"Убивство"},"MT_CAPTURE":{"value":"Захоплення"},"MT_DEFENSE":{"value":"Оборона"},"MT_DISRUPTION":{"value":"Завада підриву"},"MT_EVACUATION":{"value":"Супровід дезертирів"},"MT_EXCAVATE":{"value":"Видобуток"},"MT_EXTERMINATION":{"value":"Винищення"},"MT_HIVE":{"value":"Лігвище"},"MT_INTEL":{"value":"Шпигунство"},"MT_LANDSCAPE":{"value":"Мандри"},"MT_MOBILE_DEFENSE":{"value":"Мобільна оборона"},"MT_PVP":{"value":"Конклав"},"MT_RESCUE":{"value":"Визволення"},"MT_RETRIEVAL":{"value":"Викрадення"},"MT_SABOTAGE":{"value":"Саботаж"},"MT_SECTOR":{"value":"Темний сектор"},"MT_SURVIVAL":{"value":"Виживання"},"MT_TERRITORY":{"value":"Перехоплення"},"MT_DEFAULT":{"value":"Невідомо"},"MT_VOID_CASCADE":{"value":"Каскад Порожнечі"},"MT_ASCENSION":{"value":"Сходження"},"MT_ALCHEMY":{"value":"Алхімія"},"MT_ENDLESS_CAPTURE":{"value":"Legacyte Harvest"}}
''';

const _$_zh = r'''
{"MT_ARENA":{"value":"竞技场"},"MT_ARTIFACT":{"value":"中断"},"MT_ASSAULT":{"value":"强袭"},"MT_ASSASSINATION":{"value":"刺殺"},"MT_CAPTURE":{"value":"捕獲"},"MT_DEFENSE":{"value":"防禦"},"MT_DISRUPTION":{"value":"中断"},"MT_EVACUATION":{"value":"叛逃"},"MT_EXCAVATE":{"value":"挖掘"},"MT_EXTERMINATION":{"value":"殲滅"},"MT_HIVE":{"value":"清巢"},"MT_INTEL":{"value":"間諜"},"MT_LANDSCAPE":{"value":"自由探索"},"MT_MOBILE_DEFENSE":{"value":"移動防禦"},"MT_PVP":{"value":"武形秘仪"},"MT_RESCUE":{"value":"救援"},"MT_RETRIEVAL":{"value":"劫持"},"MT_SABOTAGE":{"value":"破壞"},"MT_SECTOR":{"value":"黑暗地带"},"MT_SURVIVAL":{"value":"生存"},"MT_TERRITORY":{"value":"攔截"},"MT_DEFAULT":{"value":"未知"},"MT_VOID_CASCADE":{"value":"虚空覆涌"},"MT_ASCENSION":{"value":"Ascension"},"MT_ALCHEMY":{"value":"元素转换"},"MT_ENDLESS_CAPTURE":{"value":"Legacyte Harvest"}}
''';
