// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'steel_path.dart';

// **************************************************************************
// StrEmbeddingGenerator
// **************************************************************************

const _$_en = r'''
{"rotation":[{"name":"Umbra Forma Blueprint","cost":150},{"name":"50,000 Kuva","cost":55},{"name":"Kitgun Riven Mod","cost":75},{"name":"3x Forma","cost":75},{"name":"Zaw Riven Mod","cost":75},{"name":"30,000 Endo","cost":150},{"name":"Rifle Riven Mod","cost":75},{"name":"Shotgun Riven Mod","cost":75}],"evergreen":[{"name":"Veiled Riven Cipher","cost":20},{"name":"Bishamo Pauldrons Blueprint","cost":15},{"name":"Bishamo Cuirass Blueprint","cost":25},{"name":"Bishamo Helmet Blueprint","cost":20},{"name":"Bishamo Greaves Blueprint","cost":25},{"name":"10k Kuva","cost":15},{"name":"Primary Arcane Adapter","cost":15},{"name":"Secondary Arcane Adapter","cost":15},{"name":"Relic Pack","cost":15},{"name":"Stance Forma Blueprint","cost":10},{"name":"Trio Orbit Ephermera","cost":3},{"name":"Crania Ephemera","cost":85},{"name":"Counterbalance","cost":35},{"name":"Noggle Statue - Teshin","cost":35},{"name":"Gauss in Action Glyph","cost":15},{"name":"Grendel in Action Glyph","cost":15},{"name":"Protea in Action Glyph","cost":15},{"name":"Orokin Tea Set","cost":15},{"name":"Xaku in Action Glyph","cost":15}]}
''';

const _$_cs = r'''
{"rotation":[{"name":"Umbra Forma Blueprint","cost":150},{"name":"50,000 Kuva","cost":55},{"name":"Kitgun Riven Mod","cost":75},{"name":"3x Forma","cost":75},{"name":"Zaw Riven Mod","cost":75},{"name":"30,000 Endo","cost":150},{"name":"Rifle Riven Mod","cost":75},{"name":"Shotgun Riven Mod","cost":75}],"evergreen":[{"name":"Veiled Riven Cipher","cost":20},{"name":"Bishamo Pauldrons Blueprint","cost":15},{"name":"Bishamo Cuirass Blueprint","cost":25},{"name":"Bishamo Helmet Blueprint","cost":20},{"name":"Bishamo Greaves Blueprint","cost":25},{"name":"10k Kuva","cost":15},{"name":"Primary Arcane Adapter","cost":15},{"name":"Secondary Arcane Adapter","cost":15},{"name":"Relic Pack","cost":15},{"name":"Stance Forma Blueprint","cost":10},{"name":"Trio Orbit Ephermera","cost":3},{"name":"Crania Ephemera","cost":85},{"name":"Counterbalance","cost":35},{"name":"Noggle Statue - Teshin","cost":35},{"name":"Gauss in Action Glyph","cost":15},{"name":"Grendel in Action Glyph","cost":15},{"name":"Protea in Action Glyph","cost":15},{"name":"Orokin Tea Set","cost":15},{"name":"Xaku in Action Glyph","cost":15}]}
''';

const _$_de = r'''
{"rotation":[{"name":"Umbra Forma Blueprint","cost":150},{"name":"50.000 Kuva","cost":55},{"name":"Kitgun Riven Mod","cost":75},{"name":"3x Forma","cost":75},{"name":"Zaw Riven Mod","cost":75},{"name":"30.000 Endo","cost":150},{"name":"Rifle Riven Mod","cost":75},{"name":"Shotgun Riven Mod","cost":75}],"evergreen":[{"name":"Verhüllter Riven-Cipher","cost":20},{"name":"Bishamo Pauldrons Blaupause","cost":15},{"name":"Bishamo Pauldrons Blaupause","cost":25},{"name":"Bishamo Pauldrons Blaupause","cost":20},{"name":"Bishamo Greaves Blaupause","cost":25},{"name":"10k Kuva","cost":15},{"name":"Primärer Arkaner Adapter","cost":15},{"name":"Sekundärer Arkaner Adapter","cost":15},{"name":"Relic Pack","cost":15},{"name":"Stance Forma Blaupause","cost":10},{"name":"Trio Orbit Ephermera","cost":3},{"name":"Crania Ephemera","cost":85},{"name":"Gegenbalance","cost":35},{"name":"Wackelstatue - Teshin","cost":35},{"name":"Gauss in Aktion Glyphe","cost":15},{"name":"Grendel in Action Glyph","cost":15},{"name":"Protea in Aktion Glyphe","cost":15},{"name":"Orokin Tee Satz","cost":15},{"name":"Xaku in Aktion Glyphe","cost":15}]}
''';

const _$_es = r'''
{"rotation":[{"name":"Umbra Forma Blueprint","cost":150},{"name":"50,000 Kuva","cost":55},{"name":"Kitgun Riven Mod","cost":75},{"name":"3x Forma","cost":75},{"name":"Zaw Riven Mod","cost":75},{"name":"30,000 Endo","cost":150},{"name":"Rifle Riven Mod","cost":75},{"name":"Shotgun Riven Mod","cost":75}],"evergreen":[{"name":"Cifrador de Mod Agrietado Velado","cost":20},{"name":"Plano de Hombreras Bishamo","cost":15},{"name":"Plano de Coraza Bishamo","cost":25},{"name":"Plano de Casco Bishamo","cost":20},{"name":"Plano de Grebas Bishamo","cost":25},{"name":"10,000 Kuva","cost":15},{"name":"Adaptador de Arcano Primario","cost":15},{"name":"Adaptador de Arcano Secundario","cost":15},{"name":"Relic Pack","cost":15},{"name":"Plano de Forma de Guardia","cost":10},{"name":"Trio Orbit Ephermera","cost":3},{"name":"Crania Ephemera","cost":85},{"name":"Counterbalance","cost":35},{"name":"Noggle Statue - Teshin","cost":35},{"name":"Gauss in Action Glyph","cost":15},{"name":"Grendel in Action Glyph","cost":15},{"name":"Protea in Action Glyph","cost":15},{"name":"Orokin Tea Set","cost":15},{"name":"Xaku in Action Glyph","cost":15}]}
''';

const _$_fr = r'''
{"rotation":[{"name":"Schéma Forma Umbra","cost":150},{"name":"50 000 X Kuva","cost":55},{"name":"Kitgun Riven Mod","cost":75},{"name":"3x Forma","cost":75},{"name":"Zaw Riven Mod","cost":75},{"name":"30 000 X Endo","cost":150},{"name":"Rifle Riven Mod","cost":75},{"name":"Shotgun Riven Mod","cost":75}],"evergreen":[{"name":"Décodeur de Riven Voilé","cost":20},{"name":"Schéma Épaulières Bishamo","cost":15},{"name":"Schéma Cuirasse Bishamo","cost":25},{"name":"Schéma Casque Bishamo","cost":20},{"name":"Schéma Grèves Bishamo","cost":25},{"name":"10 000 X Kuva","cost":15},{"name":"Adaptateur D'Arcane Principale","cost":15},{"name":"Adaptateur D'Arcane Secondaire","cost":15},{"name":"Relic Pack","cost":15},{"name":"Forma Posture Schéma","cost":10},{"name":"Ephermera Trio Orbital","cost":3},{"name":"Ephemera Crania","cost":85},{"name":"Contrepoids","cost":35},{"name":"Statuette Noggle - Teshin","cost":35},{"name":"Glyphe Gauss En Action","cost":15},{"name":"Grendel en Action","cost":15},{"name":"Glyphe Protea En Action","cost":15},{"name":"Service À Thé Orokin","cost":15},{"name":"Glyphe Xaku En Action","cost":15}]}
''';

const _$_it = r'''
{"rotation":[{"name":"Umbra Forma Blueprint","cost":150},{"name":"50,000 Kuva","cost":55},{"name":"Kitgun Riven Mod","cost":75},{"name":"3x Forma","cost":75},{"name":"Zaw Riven Mod","cost":75},{"name":"30,000 Endo","cost":150},{"name":"Rifle Riven Mod","cost":75},{"name":"Shotgun Riven Mod","cost":75}],"evergreen":[{"name":"Veiled Riven Cipher","cost":20},{"name":"Bishamo Pauldrons Blueprint","cost":15},{"name":"Bishamo Cuirass Blueprint","cost":25},{"name":"Bishamo Helmet Blueprint","cost":20},{"name":"Bishamo Greaves Blueprint","cost":25},{"name":"10k Kuva","cost":15},{"name":"Primary Arcane Adapter","cost":15},{"name":"Secondary Arcane Adapter","cost":15},{"name":"Relic Pack","cost":15},{"name":"Stance Forma Blueprint","cost":10},{"name":"Trio Orbit Ephermera","cost":3},{"name":"Crania Ephemera","cost":85},{"name":"Counterbalance","cost":35},{"name":"Noggle Statue - Teshin","cost":35},{"name":"Gauss in Action Glyph","cost":15},{"name":"Grendel in Action Glyph","cost":15},{"name":"Protea in Action Glyph","cost":15},{"name":"Orokin Tea Set","cost":15},{"name":"Xaku in Action Glyph","cost":15}]}
''';

const _$_ko = r'''
{"rotation":[{"name":"Umbra Forma Blueprint","cost":150},{"name":"50,000 Kuva","cost":55},{"name":"Kitgun Riven Mod","cost":75},{"name":"3x Forma","cost":75},{"name":"Zaw Riven Mod","cost":75},{"name":"30,000 Endo","cost":150},{"name":"주 무기 리벤 모드","cost":75},{"name":"산탄총 리벤 모드","cost":75}],"evergreen":[{"name":"Veiled Riven Cipher","cost":20},{"name":"Bishamo Pauldrons Blueprint","cost":15},{"name":"Bishamo Cuirass Blueprint","cost":25},{"name":"Bishamo Helmet Blueprint","cost":20},{"name":"Bishamo Greaves Blueprint","cost":25},{"name":"10k Kuva","cost":15},{"name":"Primary Arcane Adapter","cost":15},{"name":"Secondary Arcane Adapter","cost":15},{"name":"성유물 팩","cost":15},{"name":"Stance Forma Blueprint","cost":10},{"name":"Trio Orbit Ephermera","cost":3},{"name":"Crania Ephemera","cost":85},{"name":"Counterbalance","cost":35},{"name":"Noggle Statue - Teshin","cost":35},{"name":"Gauss in Action Glyph","cost":15},{"name":"Grendel in Action Glyph","cost":15},{"name":"Protea in Action Glyph","cost":15},{"name":"Orokin Tea Set","cost":15},{"name":"Xaku in Action Glyph","cost":15}]}
''';

const _$_pl = r'''
{"rotation":[{"name":"Umbra Forma Blueprint","cost":150},{"name":"50,000 Kuva","cost":55},{"name":"Kitgun Riven Mod","cost":75},{"name":"3x Forma","cost":75},{"name":"Zaw Riven Mod","cost":75},{"name":"30,000 Endo","cost":150},{"name":"Rifle Riven Mod","cost":75},{"name":"Shotgun Riven Mod","cost":75}],"evergreen":[{"name":"Veiled Riven Cipher","cost":20},{"name":"Bishamo Pauldrons Blueprint","cost":15},{"name":"Bishamo Cuirass Blueprint","cost":25},{"name":"Bishamo Helmet Blueprint","cost":20},{"name":"Bishamo Greaves Blueprint","cost":25},{"name":"10k Kuva","cost":15},{"name":"Primary Arcane Adapter","cost":15},{"name":"Secondary Arcane Adapter","cost":15},{"name":"Relic Pack","cost":15},{"name":"Stance Forma Blueprint","cost":10},{"name":"Trio Orbit Ephermera","cost":3},{"name":"Crania Ephemera","cost":85},{"name":"Counterbalance","cost":35},{"name":"Noggle Statue - Teshin","cost":35},{"name":"Gauss in Action Glyph","cost":15},{"name":"Grendel in Action Glyph","cost":15},{"name":"Protea in Action Glyph","cost":15},{"name":"Orokin Tea Set","cost":15},{"name":"Xaku in Action Glyph","cost":15}]}
''';

const _$_pt = r'''
{"rotation":[{"name":"Umbra Forma Blueprint","cost":150},{"name":"50,000 Kuva","cost":55},{"name":"Kitgun Riven Mod","cost":75},{"name":"3x Forma","cost":75},{"name":"Zaw Riven Mod","cost":75},{"name":"30,000 Endo","cost":150},{"name":"Rifle Riven Mod","cost":75},{"name":"Shotgun Riven Mod","cost":75}],"evergreen":[{"name":"Veiled Riven Cipher","cost":20},{"name":"Bishamo Pauldrons Blueprint","cost":15},{"name":"Bishamo Cuirass Blueprint","cost":25},{"name":"Bishamo Helmet Blueprint","cost":20},{"name":"Bishamo Greaves Blueprint","cost":25},{"name":"10k Kuva","cost":15},{"name":"Primary Arcane Adapter","cost":15},{"name":"Secondary Arcane Adapter","cost":15},{"name":"Relic Pack","cost":15},{"name":"Stance Forma Blueprint","cost":10},{"name":"Trio Orbit Ephermera","cost":3},{"name":"Crania Ephemera","cost":85},{"name":"Counterbalance","cost":35},{"name":"Noggle Statue - Teshin","cost":35},{"name":"Gauss in Action Glyph","cost":15},{"name":"Grendel in Action Glyph","cost":15},{"name":"Protea in Action Glyph","cost":15},{"name":"Orokin Tea Set","cost":15},{"name":"Xaku in Action Glyph","cost":15}]}
''';

const _$_ru = r'''
{"rotation":[{"name":"Чертёж: Умбра Форма","cost":150},{"name":"50,000 Кувы","cost":55},{"name":"Мод Разлома для Китганов","cost":75},{"name":"3x Форма","cost":75},{"name":"Мод Разлома для Зо","cost":75},{"name":"30,000 Эндо","cost":150},{"name":"Мод Разлома для Винтовок","cost":75},{"name":"Мод Разлома для Дробовиков","cost":75}],"evergreen":[{"name":"Дешифратор Скрытых Модов Разлома","cost":20},{"name":"Чертёж: Наплечники: Бишамо","cost":15},{"name":"Чертёж: Кираса: Бишамо","cost":25},{"name":"Чертёж: Шлем: Бишамо","cost":20},{"name":"Чертёж: Поножи: Бишамо","cost":25},{"name":"10k Кувы","cost":15},{"name":"Адаптер Для Мистификатора Основного Оружия","cost":15},{"name":"Адаптер Для Мистификатора Вторичного Оружия","cost":15},{"name":"Набор Реликвий","cost":15},{"name":"Чертёж: Форма: Стойка","cost":10},{"name":"Эфемера: Орбитальное Трио","cost":3},{"name":"Эфемера: Крания","cost":85},{"name":"Противовес","cost":35},{"name":"Фигурка - Тешин","cost":35},{"name":"Глиф: Гаусс в Деле","cost":15},{"name":"Глиф: Грендель в Деле","cost":15},{"name":"Глиф: Протея в Деле","cost":15},{"name":"Чайный Сервиз Орокин","cost":15},{"name":"Глиф: Заку в Деле","cost":15}]}
''';

const _$_sr = r'''
{"rotation":[{"name":"Umbra Forma Blueprint","cost":150},{"name":"50,000 Kuva","cost":55},{"name":"Kitgun Riven Mod","cost":75},{"name":"3x Forma","cost":75},{"name":"Zaw Riven Mod","cost":75},{"name":"30,000 Endo","cost":150},{"name":"Rifle Riven Mod","cost":75},{"name":"Shotgun Riven Mod","cost":75}],"evergreen":[{"name":"Veiled Riven Cipher","cost":20},{"name":"Bishamo Pauldrons Blueprint","cost":15},{"name":"Bishamo Cuirass Blueprint","cost":25},{"name":"Bishamo Helmet Blueprint","cost":20},{"name":"Bishamo Greaves Blueprint","cost":25},{"name":"10k Kuva","cost":15},{"name":"Primary Arcane Adapter","cost":15},{"name":"Secondary Arcane Adapter","cost":15},{"name":"Relic Pack","cost":15},{"name":"Stance Forma Blueprint","cost":10},{"name":"Trio Orbit Ephermera","cost":3},{"name":"Crania Ephemera","cost":85},{"name":"Counterbalance","cost":35},{"name":"Noggle Statue - Teshin","cost":35},{"name":"Gauss in Action Glyph","cost":15},{"name":"Grendel in Action Glyph","cost":15},{"name":"Protea in Action Glyph","cost":15},{"name":"Orokin Tea Set","cost":15},{"name":"Xaku in Action Glyph","cost":15}]}
''';

const _$_tr = r'''
{"rotation":[{"name":"Umbra Forma Kalıp","cost":150},{"name":"50,000 Kuva","cost":55},{"name":"Kitgun Riven Mod","cost":75},{"name":"3x Forma","cost":75},{"name":"Zaw Riven Mod","cost":75},{"name":"30,000 Endo","cost":150},{"name":"Rifle Riven Mod","cost":75},{"name":"Shotgun Riven Mod","cost":75}],"evergreen":[{"name":"Veiled Riven Cipher","cost":20},{"name":"Bishamo Pauldrons Blueprint","cost":15},{"name":"Bishamo Cuirass Blueprint","cost":25},{"name":"Bishamo Helmet Blueprint","cost":20},{"name":"Bishamo Greaves Blueprint","cost":25},{"name":"10k Kuva","cost":15},{"name":"Primary Arcane Adapter","cost":15},{"name":"Secondary Arcane Adapter","cost":15},{"name":"Relic Pack","cost":15},{"name":"Stance Forma Blueprint","cost":10},{"name":"Trio Orbit Ephermera","cost":3},{"name":"Crania Ephemera","cost":85},{"name":"Counterbalance","cost":35},{"name":"Noggle Statue - Teshin","cost":35},{"name":"Gauss in Action Glyph","cost":15},{"name":"Grendel in Action Glyph","cost":15},{"name":"Protea in Action Glyph","cost":15},{"name":"Orokin Tea Set","cost":15},{"name":"Xaku in Action Glyph","cost":15}]}
''';

const _$_uk = r'''
{"rotation":[{"name":"Форма-умбра (креслення)","cost":150},{"name":"50 000 x Кува","cost":55},{"name":"Модифікатор розколу для складострілів","cost":75},{"name":"Форма x 3","cost":75},{"name":"Модифікатор розколу для зо","cost":75},{"name":"30 000 Ендо","cost":150},{"name":"Модифікатор розколу для гвинтівок","cost":75},{"name":"Модифікатор розколу для рушниць","cost":75}],"evergreen":[{"name":"Шифрувальник прихованих модифікаторів розколу","cost":20},{"name":"Рукави «Бішамо» (креслення)","cost":15},{"name":"Кіраса «Бішамо» (креслення)","cost":25},{"name":"Шолом «Бішамо» (креслення)","cost":20},{"name":"Штани «Бішамо» (креслення)","cost":25},{"name":"10 000 x Кува","cost":15},{"name":"Тримач містифікаторів для основної зброї","cost":15},{"name":"Тримач містифікаторів для допоміжної зброї","cost":15},{"name":"Набір реліквій","cost":15},{"name":"Форма рукопашного стилю (креслення)","cost":10},{"name":"Ефемера «Орбітальна трійця»","cost":3},{"name":"Ефемера «Череп»","cost":85},{"name":"Урівноваження","cost":35},{"name":"Ноґл «Тешин»","cost":35},{"name":"Гліф «Ґаусс у дії»","cost":15},{"name":"Гліф «Ґрендель у дії»","cost":15},{"name":"Гліф «Протея у дії»","cost":15},{"name":"Орокінський чайний сервіз","cost":15},{"name":"Гліф «Заку в дії»","cost":15}]}
''';

const _$_zh = r'''
{"rotation":[{"name":"Umbra Forma 蓝图","cost":150},{"name":"50,000 赤毒","cost":55},{"name":"组合枪裂罅 Mod","cost":75},{"name":"3x Forma","cost":75},{"name":"Zaw 裂罅 Mod","cost":75},{"name":"30,000 内融核心","cost":150},{"name":"步枪裂罅 Mod","cost":75},{"name":"霰弹枪裂罅 Mod","cost":75}],"evergreen":[{"name":"裂罅破解器","cost":20},{"name":"军神护肩 蓝图","cost":15},{"name":"军神胸甲 蓝图","cost":25},{"name":"军神头盔 蓝图","cost":20},{"name":"军神护胫 蓝图","cost":25},{"name":"10,000 赤毒","cost":15},{"name":"主要武器赋能槽连接器","cost":15},{"name":"次要武器赋能槽连接器","cost":15},{"name":"遗物组合包","cost":15},{"name":"架式 Forma 蓝图","cost":10},{"name":"三轨幻纹","cost":3},{"name":"颅骨幻纹","cost":85},{"name":"制衡","cost":35},{"name":"Teshin 摇头娃娃","cost":35},{"name":"Gauss 战斗姿态浮印","cost":15},{"name":"Grendel 战斗姿态浮印","cost":15},{"name":"Protea 战斗姿态浮印","cost":15},{"name":"Orokin 茶具","cost":15},{"name":"Xaku 战斗姿态浮印","cost":15}]}
''';
