// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'syndicates.dart';

// **************************************************************************
// StrEmbeddingGenerator
// **************************************************************************

const _$_en = r'''
{"ArbitersSyndicate":{"name":"Arbiters of Hexis"},"CephalonSudaSyndicate":{"name":"Cephalon Suda"},"NewLokaSyndicate":{"name":"New Loka"},"PerrinSyndicate":{"name":"Perrin Sequence"},"SteelMeridianSyndicate":{"name":"Steel Meridian"},"RedVeilSyndicate":{"name":"Red Veil"},"CetusSyndicate":{"name":"Ostrons"},"QuillsSyndicate":{"name":"Quills"},"AssassinsSyndicate":{"name":"Assassins"},"EventSyndicate":{"name":"Operations Syndicate"},"SolarisSyndicate":{"name":"Solaris United"},"VoxSyndicate":{"name":"Vox Solaris"},"VentKidsSyndicate":{"name":"Vent Kids"},"EntratiSyndicate":{"name":"Entrati"},"NecraloidSyndicate":{"name":"Necraloid"},"KahlSyndicate":{"name":"Kahl's Garrison"},"ZarimanSyndicate":{"name":"The Holdfasts"},"RadioLegionSyndicate":{"name":"The Wolf of Saturn Six"},"RadioLegion2Syndicate":{"name":"The Emissary"},"RadioLegion3Syndicate":{"name":"Glassmaker"},"RadioLegionIntermissionSyndicate":{"name":"Intermission"},"RadioLegionIntermission2Syndicate":{"name":"Intermission II"},"RadioLegionIntermission3Syndicate":{"name":"Intermission III"},"RadioLegionIntermission4Syndicate":{"name":"Nora's Choice"},"RadioLegionIntermission5Syndicate":{"name":"Nora's Mix Volume 1"},"RadioLegionIntermission6Syndicate":{"name":"Nora's Mix Volume 2"},"EntratiLabSyndicate":{"name":"Cavia"},"HexSyndicate":{"name":"The Hex"}}
''';

const _$_cs = r'''
{"ArbitersSyndicate":{"name":"Arbiters of Hexis"},"CephalonSudaSyndicate":{"name":"Cephalon Suda"},"NewLokaSyndicate":{"name":"New Loka"},"PerrinSyndicate":{"name":"Perrin Sequence"},"SteelMeridianSyndicate":{"name":"Steel Meridian"},"RedVeilSyndicate":{"name":"Red Veil"},"CetusSyndicate":{"name":"Ostrons"},"QuillsSyndicate":{"name":"Quills"},"AssassinsSyndicate":{"name":"Assassins"},"EventSyndicate":{"name":"Operations Syndicate"},"SolarisSyndicate":{"name":"Solaris United"},"VoxSyndicate":{"name":"Vox Solaris"},"VentKidsSyndicate":{"name":"Vent Kids"},"EntratiSyndicate":{"name":"Entrati"},"NecraloidSyndicate":{"name":"Necraloid"},"KahlSyndicate":{"name":"Kahl's Garrison"},"ZarimanSyndicate":{"name":"The Holdfasts"},"RadioLegionSyndicate":{"name":"The Wolf of Saturn Six"},"RadioLegion2Syndicate":{"name":"The Emissary"},"RadioLegion3Syndicate":{"name":"Glassmaker"},"RadioLegionIntermissionSyndicate":{"name":"Intermission"},"RadioLegionIntermission2Syndicate":{"name":"Intermission II"},"RadioLegionIntermission3Syndicate":{"name":"Intermission III"},"RadioLegionIntermission4Syndicate":{"name":"Nora's Choice"},"RadioLegionIntermission5Syndicate":{"name":"Nora's Mix Volume 1"},"RadioLegionIntermission6Syndicate":{"name":"Nora's Mix Volume 2"},"EntratiLabSyndicate":{"name":"Cavia"},"HexSyndicate":{"name":"The Hex"}}
''';

const _$_de = r'''
{"ArbitersSyndicate":{"name":"Arbiters of Hexis"},"CephalonSudaSyndicate":{"name":"Cephalon Suda"},"NewLokaSyndicate":{"name":"New Loka"},"PerrinSyndicate":{"name":"Perrin Sequence"},"SteelMeridianSyndicate":{"name":"Steel Meridian"},"RedVeilSyndicate":{"name":"Red Veil"},"CetusSyndicate":{"name":"Ostrons"},"QuillsSyndicate":{"name":"Quills"},"AssassinsSyndicate":{"name":"Attentäter"},"EventSyndicate":{"name":"Operations Syndikat"},"SolarisSyndicate":{"name":"Solaris United"},"VoxSyndicate":{"name":"Vox Solaris"},"VentKidsSyndicate":{"name":"Schacht-Kinder"},"EntratiSyndicate":{"name":"Entrati"},"NecraloidSyndicate":{"name":"Necraloid"},"KahlSyndicate":{"name":"Kahl's Garrison"},"ZarimanSyndicate":{"name":"The Holdfasts"},"RadioLegionSyndicate":{"name":"The Wolf of Saturn Six"},"RadioLegion2Syndicate":{"name":"The Emissary"},"RadioLegion3Syndicate":{"name":"Glassmaker"},"RadioLegionIntermissionSyndicate":{"name":"Intermission"},"RadioLegionIntermission2Syndicate":{"name":"Intermission II"},"RadioLegionIntermission3Syndicate":{"name":"Intermission III"},"RadioLegionIntermission4Syndicate":{"name":"Nora's Choice"},"RadioLegionIntermission5Syndicate":{"name":"Nora's Mix Volume 1"},"RadioLegionIntermission6Syndicate":{"name":"Nora's Mix Volume 2"},"EntratiLabSyndicate":{"name":"Cavia"},"HexSyndicate":{"name":"The Hex"}}
''';

const _$_es = r'''
{"ArbitersSyndicate":{"name":"Árbitros de hexis"},"CephalonSudaSyndicate":{"name":"Céfalon suda"},"NewLokaSyndicate":{"name":"Nuevo loka"},"PerrinSyndicate":{"name":"Secuencia perrin"},"SteelMeridianSyndicate":{"name":"Meridiano de acero"},"RedVeilSyndicate":{"name":"Velo rojo"},"CetusSyndicate":{"name":"Ostronitas"},"QuillsSyndicate":{"name":"Raquis"},"AssassinsSyndicate":{"name":"Asesinos"},"EventSyndicate":{"name":"Sindicato de las operaciones"},"SolarisSyndicate":{"name":"Solaris Unida"},"VoxSyndicate":{"name":"Vox Solaris"},"VentKidsSyndicate":{"name":"Ventkids"},"EntratiSyndicate":{"name":"Entrati"},"NecraloidSyndicate":{"name":"Necraloide"},"KahlSyndicate":{"name":"Kahl's Garrison"},"ZarimanSyndicate":{"name":"The Holdfasts"},"RadioLegionSyndicate":{"name":"The Wolf of Saturn Six"},"RadioLegion2Syndicate":{"name":"The Emissary"},"RadioLegion3Syndicate":{"name":"Glassmaker"},"RadioLegionIntermissionSyndicate":{"name":"Intermission"},"RadioLegionIntermission2Syndicate":{"name":"Intermission II"},"RadioLegionIntermission3Syndicate":{"name":"Intermission III"},"RadioLegionIntermission4Syndicate":{"name":"Nora's Choice"},"RadioLegionIntermission5Syndicate":{"name":"Nora's Mix Volume 1"},"RadioLegionIntermission6Syndicate":{"name":"Nora's Mix Volume 2"},"EntratiLabSyndicate":{"name":"Cavia"},"HexSyndicate":{"name":"The Hex"}}
''';

const _$_fr = r'''
{"ArbitersSyndicate":{"name":"Les Arbitres de Hexis"},"CephalonSudaSyndicate":{"name":"Le Cephalon Suda"},"NewLokaSyndicate":{"name":"Le Nouveau Loka"},"PerrinSyndicate":{"name":"La Séquence Perrin"},"SteelMeridianSyndicate":{"name":"Le Méridien d'Acier"},"RedVeilSyndicate":{"name":"Le Voile Rouge"},"CetusSyndicate":{"name":"Ostron"},"QuillsSyndicate":{"name":"Les Plumes"},"AssassinsSyndicate":{"name":"Assassins"},"EventSyndicate":{"name":"Opérations syndicales"},"SolarisSyndicate":{"name":"Union Solaris"},"VoxSyndicate":{"name":"Vox Solaris"},"VentKidsSyndicate":{"name":"Orphelins des Conduits"},"EntratiSyndicate":{"name":"Entrati"},"NecraloidSyndicate":{"name":"Necraloïde"},"KahlSyndicate":{"name":"Kahl's Garrison"},"ZarimanSyndicate":{"name":"The Holdfasts"},"RadioLegionSyndicate":{"name":"The Wolf of Saturn Six"},"RadioLegion2Syndicate":{"name":"The Emissary"},"RadioLegion3Syndicate":{"name":"Glassmaker"},"RadioLegionIntermissionSyndicate":{"name":"Intermission"},"RadioLegionIntermission2Syndicate":{"name":"Intermission II"},"RadioLegionIntermission3Syndicate":{"name":"Intermission III"},"RadioLegionIntermission4Syndicate":{"name":"Nora's Choice"},"RadioLegionIntermission5Syndicate":{"name":"Nora's Mix Volume 1"},"RadioLegionIntermission6Syndicate":{"name":"Nora's Mix Volume 2"},"EntratiLabSyndicate":{"name":"Cavia"},"HexSyndicate":{"name":"The Hex"}}
''';

const _$_it = r'''
{"ArbitersSyndicate":{"name":"Arbiters of Hexis"},"CephalonSudaSyndicate":{"name":"Cephalon Suda"},"NewLokaSyndicate":{"name":"New Loka"},"PerrinSyndicate":{"name":"Perrin Sequence"},"SteelMeridianSyndicate":{"name":"Steel Meridian"},"RedVeilSyndicate":{"name":"Red Veil"},"CetusSyndicate":{"name":"Ostrons"},"QuillsSyndicate":{"name":"Quills"},"AssassinsSyndicate":{"name":"Assassins"},"EventSyndicate":{"name":"Operations Syndicate"},"SolarisSyndicate":{"name":"Solaris United"},"VoxSyndicate":{"name":"Vox Solaris"},"VentKidsSyndicate":{"name":"Vent Kids"},"EntratiSyndicate":{"name":"Entrati"},"NecraloidSyndicate":{"name":"Necraloid"},"KahlSyndicate":{"name":"Kahl's Garrison"},"ZarimanSyndicate":{"name":"The Holdfasts"},"RadioLegionSyndicate":{"name":"The Wolf of Saturn Six"},"RadioLegion2Syndicate":{"name":"The Emissary"},"RadioLegion3Syndicate":{"name":"Glassmaker"},"RadioLegionIntermissionSyndicate":{"name":"Intermission"},"RadioLegionIntermission2Syndicate":{"name":"Intermission II"},"RadioLegionIntermission3Syndicate":{"name":"Intermission III"},"RadioLegionIntermission4Syndicate":{"name":"Nora's Choice"},"RadioLegionIntermission5Syndicate":{"name":"Nora's Mix Volume 1"},"RadioLegionIntermission6Syndicate":{"name":"Nora's Mix Volume 2"},"EntratiLabSyndicate":{"name":"Cavia"},"HexSyndicate":{"name":"The Hex"}}
''';

const _$_ko = r'''
{"ArbitersSyndicate":{"name":"아비터즈 오브 헥시스"},"CephalonSudaSyndicate":{"name":"세팔론 수다"},"NewLokaSyndicate":{"name":"뉴 로카"},"PerrinSyndicate":{"name":"페린 시퀀스"},"SteelMeridianSyndicate":{"name":"스틸 메리디안"},"RedVeilSyndicate":{"name":"레드 베일"},"CetusSyndicate":{"name":"오스트론"},"QuillsSyndicate":{"name":"퀼"},"AssassinsSyndicate":{"name":"암살자"},"EventSyndicate":{"name":"오퍼레이션 신디케이트"},"SolarisSyndicate":{"name":"Solaris United"},"VoxSyndicate":{"name":"Vox Solaris"},"VentKidsSyndicate":{"name":"Vent Kids"},"EntratiSyndicate":{"name":"Entrati"},"NecraloidSyndicate":{"name":"Necraloid"},"KahlSyndicate":{"name":"Kahl's Garrison"},"ZarimanSyndicate":{"name":"The Holdfasts"},"RadioLegionSyndicate":{"name":"The Wolf of Saturn Six"},"RadioLegion2Syndicate":{"name":"The Emissary"},"RadioLegion3Syndicate":{"name":"Glassmaker"},"RadioLegionIntermissionSyndicate":{"name":"Intermission"},"RadioLegionIntermission2Syndicate":{"name":"Intermission II"},"RadioLegionIntermission3Syndicate":{"name":"Intermission III"},"RadioLegionIntermission4Syndicate":{"name":"Nora's Choice"},"RadioLegionIntermission5Syndicate":{"name":"Nora's Mix Volume 1"},"RadioLegionIntermission6Syndicate":{"name":"Nora's Mix Volume 2"},"EntratiLabSyndicate":{"name":"Cavia"},"HexSyndicate":{"name":"The Hex"}}
''';

const _$_pl = r'''
{"ArbitersSyndicate":{"name":"Arbitrzy Hexis"},"CephalonSudaSyndicate":{"name":"Cephalon Suda"},"NewLokaSyndicate":{"name":"Nowa Loka"},"PerrinSyndicate":{"name":"Sekwencja Perrin"},"SteelMeridianSyndicate":{"name":"Stalowy Meridian"},"RedVeilSyndicate":{"name":"Czerwony Woal"},"CetusSyndicate":{"name":"Ostrons"},"QuillsSyndicate":{"name":"Quills"},"AssassinsSyndicate":{"name":"Assassins"},"EventSyndicate":{"name":"Operations Syndicate"},"SolarisSyndicate":{"name":"Solaris United"},"VoxSyndicate":{"name":"Vox Solaris"},"VentKidsSyndicate":{"name":"Vent Kids"},"EntratiSyndicate":{"name":"Entrati"},"NecraloidSyndicate":{"name":"Necraloid"},"KahlSyndicate":{"name":"Kahl's Garrison"},"ZarimanSyndicate":{"name":"The Holdfasts"},"RadioLegionSyndicate":{"name":"The Wolf of Saturn Six"},"RadioLegion2Syndicate":{"name":"The Emissary"},"RadioLegion3Syndicate":{"name":"Glassmaker"},"RadioLegionIntermissionSyndicate":{"name":"Intermission"},"RadioLegionIntermission2Syndicate":{"name":"Intermission II"},"RadioLegionIntermission3Syndicate":{"name":"Intermission III"},"RadioLegionIntermission4Syndicate":{"name":"Nora's Choice"},"RadioLegionIntermission5Syndicate":{"name":"Nora's Mix Volume 1"},"RadioLegionIntermission6Syndicate":{"name":"Nora's Mix Volume 2"},"EntratiLabSyndicate":{"name":"Cavia"},"HexSyndicate":{"name":"The Hex"}}
''';

const _$_pt = r'''
{"ArbitersSyndicate":{"name":"Arbiters of Hexis"},"CephalonSudaSyndicate":{"name":"Cephalon Suda"},"NewLokaSyndicate":{"name":"New Loka"},"PerrinSyndicate":{"name":"Perrin Sequence"},"SteelMeridianSyndicate":{"name":"Steel Meridian"},"RedVeilSyndicate":{"name":"Red Veil"},"CetusSyndicate":{"name":"Ostrons"},"QuillsSyndicate":{"name":"Quills"},"AssassinsSyndicate":{"name":"Assassins"},"EventSyndicate":{"name":"Operations Syndicate"},"SolarisSyndicate":{"name":"Solaris United"},"VoxSyndicate":{"name":"Vox Solaris"},"VentKidsSyndicate":{"name":"Vent Kids"},"EntratiSyndicate":{"name":"Entrati"},"NecraloidSyndicate":{"name":"Necraloid"},"KahlSyndicate":{"name":"Kahl's Garrison"},"ZarimanSyndicate":{"name":"The Holdfasts"},"RadioLegionSyndicate":{"name":"The Wolf of Saturn Six"},"RadioLegion2Syndicate":{"name":"The Emissary"},"RadioLegion3Syndicate":{"name":"Glassmaker"},"RadioLegionIntermissionSyndicate":{"name":"Intermission"},"RadioLegionIntermission2Syndicate":{"name":"Intermission II"},"RadioLegionIntermission3Syndicate":{"name":"Intermission III"},"RadioLegionIntermission4Syndicate":{"name":"Nora's Choice"},"RadioLegionIntermission5Syndicate":{"name":"Nora's Mix Volume 1"},"RadioLegionIntermission6Syndicate":{"name":"Nora's Mix Volume 2"},"EntratiLabSyndicate":{"name":"Cavia"},"HexSyndicate":{"name":"The Hex"}}
''';

const _$_ru = r'''
{"ArbitersSyndicate":{"name":"Арбитры Гексиса"},"CephalonSudaSyndicate":{"name":"Цефалон Суда"},"NewLokaSyndicate":{"name":"Новая Лока"},"PerrinSyndicate":{"name":"Последовательность Перрина"},"SteelMeridianSyndicate":{"name":"Стальной Меридиан"},"RedVeilSyndicate":{"name":"Красная Вуаль"},"CetusSyndicate":{"name":"Острон"},"QuillsSyndicate":{"name":"Перья"},"AssassinsSyndicate":{"name":"Наёмники"},"EventSyndicate":{"name":"Операционное Снабжение"},"SolarisSyndicate":{"name":"Объединение Солярис"},"VoxSyndicate":{"name":"Глас Солярис"},"VentKidsSyndicate":{"name":"Дети Труб"},"EntratiSyndicate":{"name":"Энтрати"},"NecraloidSyndicate":{"name":"Некралоид"},"KahlSyndicate":{"name":"Гарнизон Кахла"},"ZarimanSyndicate":{"name":"Неукротимые"},"RadioLegionSyndicate":{"name":"Волк Сатурна 6"},"RadioLegion2Syndicate":{"name":"Эмиссар"},"RadioLegion3Syndicate":{"name":"Стеклодув"},"RadioLegionIntermissionSyndicate":{"name":"Антракт"},"RadioLegionIntermission2Syndicate":{"name":"Антракт 2"},"RadioLegionIntermission3Syndicate":{"name":"Антракт 3"},"RadioLegionIntermission4Syndicate":{"name":"Выбор Норы"},"RadioLegionIntermission5Syndicate":{"name":"Микс Норы 1"},"RadioLegionIntermission6Syndicate":{"name":"Микс Норы 2"},"EntratiLabSyndicate":{"name":"Cavia"},"HexSyndicate":{"name":"The Hex"}}
''';

const _$_sr = r'''
{"ArbitersSyndicate":{"name":"Arbiters of Hexis"},"CephalonSudaSyndicate":{"name":"Cephalon Suda"},"NewLokaSyndicate":{"name":"New Loka"},"PerrinSyndicate":{"name":"Perrin Sequence"},"SteelMeridianSyndicate":{"name":"Steel Meridian"},"RedVeilSyndicate":{"name":"Red Veil"},"CetusSyndicate":{"name":"Ostrons"},"QuillsSyndicate":{"name":"Quills"},"AssassinsSyndicate":{"name":"Assassins"},"EventSyndicate":{"name":"Operations Syndicate"},"SolarisSyndicate":{"name":"Solaris United"},"VoxSyndicate":{"name":"Vox Solaris"},"VentKidsSyndicate":{"name":"Vent Kids"},"EntratiSyndicate":{"name":"Entrati"},"NecraloidSyndicate":{"name":"Necraloid"},"KahlSyndicate":{"name":"Kahl's Garrison"},"ZarimanSyndicate":{"name":"The Holdfasts"},"RadioLegionSyndicate":{"name":"The Wolf of Saturn Six"},"RadioLegion2Syndicate":{"name":"The Emissary"},"RadioLegion3Syndicate":{"name":"Glassmaker"},"RadioLegionIntermissionSyndicate":{"name":"Intermission"},"RadioLegionIntermission2Syndicate":{"name":"Intermission II"},"RadioLegionIntermission3Syndicate":{"name":"Intermission III"},"RadioLegionIntermission4Syndicate":{"name":"Nora's Choice"},"RadioLegionIntermission5Syndicate":{"name":"Nora's Mix Volume 1"},"RadioLegionIntermission6Syndicate":{"name":"Nora's Mix Volume 2"},"EntratiLabSyndicate":{"name":"Cavia"},"HexSyndicate":{"name":"The Hex"}}
''';

const _$_tr = r'''
{"ArbitersSyndicate":{"name":"Arbiters of Hexis"},"CephalonSudaSyndicate":{"name":"Cephalon Suda"},"NewLokaSyndicate":{"name":"New Loka"},"PerrinSyndicate":{"name":"Perrin Sequence"},"SteelMeridianSyndicate":{"name":"Steel Meridian"},"RedVeilSyndicate":{"name":"Red Veil"},"CetusSyndicate":{"name":"Ostrons"},"QuillsSyndicate":{"name":"Quills"},"AssassinsSyndicate":{"name":"Assassins"},"EventSyndicate":{"name":"Operations Syndicate"},"SolarisSyndicate":{"name":"Solaris United"},"VoxSyndicate":{"name":"Vox Solaris"},"VentKidsSyndicate":{"name":"Vent Kids"},"EntratiSyndicate":{"name":"Entrati"},"NecraloidSyndicate":{"name":"Necraloid"},"KahlSyndicate":{"name":"Kahl's Garrison"},"ZarimanSyndicate":{"name":"The Holdfasts"},"RadioLegionSyndicate":{"name":"The Wolf of Saturn Six"},"RadioLegion2Syndicate":{"name":"The Emissary"},"RadioLegion3Syndicate":{"name":"Glassmaker"},"RadioLegionIntermissionSyndicate":{"name":"Intermission"},"RadioLegionIntermission2Syndicate":{"name":"Intermission II"},"RadioLegionIntermission3Syndicate":{"name":"Intermission III"},"RadioLegionIntermission4Syndicate":{"name":"Nora's Choice"},"RadioLegionIntermission5Syndicate":{"name":"Nora's Mix Volume 1"},"RadioLegionIntermission6Syndicate":{"name":"Nora's Mix Volume 2"},"EntratiLabSyndicate":{"name":"Cavia"},"HexSyndicate":{"name":"The Hex"}}
''';

const _$_uk = r'''
{"ArbitersSyndicate":{"name":"Арбітри Гексису"},"CephalonSudaSyndicate":{"name":"Цефалонка Суда"},"NewLokaSyndicate":{"name":"Нова Лока"},"PerrinSyndicate":{"name":"Послідовність Перрена"},"SteelMeridianSyndicate":{"name":"Сталевий Меридіан"},"RedVeilSyndicate":{"name":"Багряна Вуаль"},"CetusSyndicate":{"name":"Остронці"},"QuillsSyndicate":{"name":"Писарі"},"AssassinsSyndicate":{"name":"Убивці"},"EventSyndicate":{"name":"Оперативне постачання"},"SolarisSyndicate":{"name":"Солярійська Єдність"},"VoxSyndicate":{"name":"Глас солярійців"},"VentKidsSyndicate":{"name":"Вентижевжики"},"EntratiSyndicate":{"name":"Ентраті"},"NecraloidSyndicate":{"name":"Некралойд"},"KahlSyndicate":{"name":"Kahl's Garrison"},"ZarimanSyndicate":{"name":"The Holdfasts"},"RadioLegionSyndicate":{"name":"The Wolf of Saturn Six"},"RadioLegion2Syndicate":{"name":"The Emissary"},"RadioLegion3Syndicate":{"name":"Glassmaker"},"RadioLegionIntermissionSyndicate":{"name":"Антракт"},"RadioLegionIntermission2Syndicate":{"name":"Intermission II"},"RadioLegionIntermission3Syndicate":{"name":"Intermission III"},"RadioLegionIntermission4Syndicate":{"name":"Nora's Choice"},"RadioLegionIntermission5Syndicate":{"name":"Nora's Mix Volume 1"},"RadioLegionIntermission6Syndicate":{"name":"Nora's Mix Volume 2"},"EntratiLabSyndicate":{"name":"Кавії"},"HexSyndicate":{"name":"Прокльон"}}
''';

const _$_zh = r'''
{"ArbitersSyndicate":{"name":"均衡仲裁者"},"CephalonSudaSyndicate":{"name":"中樞蘇達"},"NewLokaSyndicate":{"name":"新世間"},"PerrinSyndicate":{"name":"佩蘭數列"},"SteelMeridianSyndicate":{"name":"鋼鐵防線"},"RedVeilSyndicate":{"name":"血色面紗"},"CetusSyndicate":{"name":"Ostrons"},"QuillsSyndicate":{"name":"夜羽"},"AssassinsSyndicate":{"name":"刺客"},"EventSyndicate":{"name":"集團"},"SolarisSyndicate":{"name":"索拉里斯联盟"},"VoxSyndicate":{"name":"索里拉斯之聲"},"VentKidsSyndicate":{"name":"通風小子"},"EntratiSyndicate":{"name":"英择谛"},"NecraloidSyndicate":{"name":"殁世械灵"},"KahlSyndicate":{"name":"卡尔驻军"},"ZarimanSyndicate":{"name":"坚守者"},"RadioLegionSyndicate":{"name":"土星六号之狼"},"RadioLegion2Syndicate":{"name":"使徒"},"RadioLegion3Syndicate":{"name":"玻璃匠"},"RadioLegionIntermissionSyndicate":{"name":"间歇"},"RadioLegionIntermission2Syndicate":{"name":"间歇II"},"RadioLegionIntermission3Syndicate":{"name":"间歇III"},"RadioLegionIntermission4Syndicate":{"name":"Nora 的精选"},"RadioLegionIntermission5Syndicate":{"name":"Nora 的混选 Vol. 1"},"RadioLegionIntermission6Syndicate":{"name":"Nora 的混选 Vol. 2"},"EntratiLabSyndicate":{"name":"科维兽"},"HexSyndicate":{"name":"The Hex"}}
''';
