name: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/main.yaml"
      - ".github/workflows/run_check.yaml"
      - "packages/**"
      - "pubspec.yaml"
  push:
    branches:
      - master
    paths:
      - ".github/workflows/main.yaml"
      - ".github/workflows/run_check.yaml"
      - "packages/**"
      - "pubspec.yaml"

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  warframe_drop_data:
    uses: ./.github/workflows/run_check.yaml
    with:
      working_directory: packages/warframe_drop_data

  warframe_items:
    uses: ./.github/workflows/run_check.yaml
    with:
      working_directory: packages/warframe_items

  warframe_worldstate_data:
    uses: ./.github/workflows/run_check.yaml
    with:
      working_directory: packages/warframe_worldstate_data

  worldstate_models:
    uses: ./.github/workflows/run_check.yaml
    with:
      working_directory: packages/worldstate_models

  worldstate_status: # Convert this to a reusable workflow under status
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Install Melos
        run: dart pub global activate melos
      - name: Install Dependencies
        run: dart pub get
      - name: Check Formatting
        run: melos format --line-length 120 --set-exit-if-changed
      - name: Analyze
        run: melos analyze
      - name: Test
        run: melos test
