name: run_check

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      working_directory: ${{ inputs.working_directory }}
      dart_sdk: "3.9.0"
      min_coverage: 0 #Change this after actually making test
      format_line_length: 120

  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      working_directory: ${{ inputs.working_directory }}
      includes: |
        **/*.md
        !brick/**/*.md
        .*/**/*.md
      modified_files_only: false
